### ISSUE TITLE
OpenGL.error

### ISSUE THREAD

**Issue by Taylorminer** [mkocabas/PARE#12]
![1](https://user-images.githubusercontent.com/41726592/144956685-a86cd400-6351-449a-a21b-0a92a239c4a3.jpg)
Can you help me to solve the problem?

**Comment by littlejiumi** [comment]
https://github.com/mmatl/pyrender/issues/86#issuecomment-767613647
Maybe this can help you~

**Comment by xiwang1212** [comment]
I encountered the same problem which seems to be caused by EGL, and need to change to OSMesa following the steps described here: https://pyrender.readthedocs.io/en/latest/install/index.html. 

To run the demo, the following setting needs to be changed from 'egl' to 'osmesa' in both _demo.py_ and _utils/vibe_renderer.py_
```
import os
os.environ['PYOPENGL_PLATFORM'] = 'osmesa'    # 'egl' --> 'osmesa' 
```

Then I need to make another somehow weird change at 
https://github.com/mkocabas/PARE/blob/03f084dc3bd930a10570bf576463b48e2eada8e8/pare/utils/vibe_renderer.py#L126
to       `  output_img = rgb * valid_mask + (1 - valid_mask) * img`

**Comment by mkocabas** [comment]
Thanks for the proposed solutions @xiwang1212, @littlejiumi!
