### ISSUE TITLE
Output for images folder

### ISSUE THREAD

**Issue by abeacco** [mkocabas/PARE#4]
Hi,

Congratulations on such a great work!

When I run PARE on an image folder I get an output pkl file that doesn't match what you specify in README.me.

For example, you specify an output key:
pose (n_frames, 72)             # SMPL pose parameters
But in the output from an image folder I get this:
pred_pose (1, 24, 3, 3)

I guess that you are transforming the 72 parameters into 24 joints rotation matrices, but I can't know exactly the format of these rotations. 
Would it be possible to also get the original pose parameters?

Another question is about the joints output, which includes 49 elements.
But the SMPL skeleton has only 24 joints...
How do I relate this 49 positions to the original 24 joints?

Thank you in advance.

Sincerely,

Alejandro Beacco

**Comment by mkocabas** [comment]
Hi @abeacco,

`pred_pose` stores the rotation matrices. You can convert it to axis-angles using https://github.com/mkocabas/PARE/blob/master/pare/utils/geometry.py#L56. 

49 joints have no direct mapping to 24 SMPL joints. Instead of using our version of SMPL (https://github.com/mkocabas/PARE/blob/master/pare/models/head/smpl_head.py#L29), you can use the original SMPL implementation from `smplx` package to get 24 original SMPL joints. You can do that via: `from smplx import SMPL`.

**Comment by abeacco** [comment]
Thank you.

You are right.

I solved it doing something similar to what you say and it worked.

Thanks
